import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import EmojiCard from '@/components/EmojiCard'
import Search from '@/components/Search'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>EMOJIFY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div>
           <h1 style={{fontSize:22,textAlign:"center", color:"#000"}}>
             Emoji-fi
            <span style={{fontSize:18, color:"#fff",marginLeft:5}}>find your emoji</span>
           </h1>
          <Search/>
         <EmojiCard/>
       </div>
    </>
  )
}
